// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;
using WorkoutRag.Data;

#nullable disable

namespace WorkoutRag.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260706033616_AddGenderToUser")]
    partial class AddGenderToUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WorkoutRag.Models.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DifficultyLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(768)");

                    b.Property<string>("Equipment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExerciseType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MovementPattern")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("MusclesTargeted")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Embedding")
                        .HasDatabaseName("idx_exercise_embedding_hnsw");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Embedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Embedding"), new[] { "vector_cosine_ops" });

                    b.HasIndex("Equipment", "DifficultyLevel")
                        .HasDatabaseName("idx_exercise_equipment_difficulty");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("WorkoutRag.Models.NutritionPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CarbsGrams")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DailyCalories")
                        .HasColumnType("integer");

                    b.Property<string>("DietaryRestrictions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FatGrams")
                        .HasColumnType("integer");

                    b.Property<string>("MealPlanJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProteinsGrams")
                        .HasColumnType("integer");

                    b.Property<string>("UserGoal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("NutritionPlan");
                });

            modelBuilder.Entity("WorkoutRag.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("AthleticLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("ComputedBiomechanicalNeeds")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<decimal?>("HeightCm")
                        .HasColumnType("numeric");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("WeightKg")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WorkoutRag.Models.UserDiet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<string>>("Allergies")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("DietType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MacroPreference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserDiets");
                });

            modelBuilder.Entity("WorkoutRag.Models.UserLifestyleProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Occupation")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserLifestyleProfile");
                });

            modelBuilder.Entity("WorkoutRag.Models.UserSport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("PriorityLevel")
                        .HasColumnType("integer");

                    b.Property<string>("SeasonStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SportName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserSports");
                });

            modelBuilder.Entity("WorkoutRag.Models.WorkoutExercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid");

                    b.Property<string>("RecommendedReps")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RecommendedSets")
                        .HasColumnType("integer");

                    b.Property<Guid>("WorkoutId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutId");

                    b.ToTable("WorkoutExercises");
                });

            modelBuilder.Entity("WorkoutRag.Models.WorkoutHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EquipmentFilter")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RawAiJson")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserPrompt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("WorkoutHistories");
                });

            modelBuilder.Entity("WorkoutRag.Models.NutritionPlan", b =>
                {
                    b.HasOne("WorkoutRag.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("WorkoutRag.Models.UserDiet", b =>
                {
                    b.HasOne("WorkoutRag.Models.User", "User")
                        .WithMany("Diets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WorkoutRag.Models.UserLifestyleProfile", b =>
                {
                    b.HasOne("WorkoutRag.Models.User", "User")
                        .WithOne("LifestyleProfile")
                        .HasForeignKey("WorkoutRag.Models.UserLifestyleProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("WorkoutRag.Models.DailyHabitProfile", "Habits", b1 =>
                        {
                            b1.Property<Guid>("UserLifestyleProfileId")
                                .HasColumnType("uuid");

                            b1.Property<int>("DailyStepCount")
                                .HasColumnType("integer");

                            b1.Property<int>("ScreenTimeHours")
                                .HasColumnType("integer");

                            b1.Property<bool>("StretchesRegularly")
                                .HasColumnType("boolean");

                            b1.Property<bool>("TakesMovementBreaks")
                                .HasColumnType("boolean");

                            b1.Property<decimal>("WaterIntakeLiters")
                                .HasColumnType("numeric");

                            b1.HasKey("UserLifestyleProfileId");

                            b1.ToTable("UserLifestyleProfile");

                            b1.WithOwner()
                                .HasForeignKey("UserLifestyleProfileId");
                        });

                    b.OwnsOne("WorkoutRag.Models.DailyMovementProfile", "Movement", b1 =>
                        {
                            b1.Property<Guid>("UserLifestyleProfileId")
                                .HasColumnType("uuid");

                            b1.Property<int>("PhysicalLaborHoursPerDay")
                                .HasColumnType("integer");

                            b1.Property<int>("SittingHoursPerDay")
                                .HasColumnType("integer");

                            b1.Property<int>("StandingHoursPerDay")
                                .HasColumnType("integer");

                            b1.Property<int>("WalkingHoursPerDay")
                                .HasColumnType("integer");

                            b1.HasKey("UserLifestyleProfileId");

                            b1.ToTable("UserLifestyleProfile");

                            b1.WithOwner()
                                .HasForeignKey("UserLifestyleProfileId");
                        });

                    b.OwnsOne("WorkoutRag.Models.OccupationalStressProfile", "Stressors", b1 =>
                        {
                            b1.Property<Guid>("UserLifestyleProfileId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("FrequentStairClimbing")
                                .HasColumnType("boolean");

                            b1.Property<bool>("OneSidedLoadCarrying")
                                .HasColumnType("boolean");

                            b1.Property<bool>("OverheadWork")
                                .HasColumnType("boolean");

                            b1.Property<bool>("ProlongedSitting")
                                .HasColumnType("boolean");

                            b1.Property<bool>("ProlongedStanding")
                                .HasColumnType("boolean");

                            b1.Property<bool>("RepetitiveBending")
                                .HasColumnType("boolean");

                            b1.Property<bool>("RepetitiveLifting")
                                .HasColumnType("boolean");

                            b1.HasKey("UserLifestyleProfileId");

                            b1.ToTable("UserLifestyleProfile");

                            b1.WithOwner()
                                .HasForeignKey("UserLifestyleProfileId");
                        });

                    b.OwnsOne("WorkoutRag.Models.PainAssessment", "Pain", b1 =>
                        {
                            b1.Property<Guid>("UserLifestyleProfileId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("AnklePain")
                                .HasColumnType("boolean");

                            b1.Property<bool>("KneePain")
                                .HasColumnType("boolean");

                            b1.Property<bool>("LowerBackPain")
                                .HasColumnType("boolean");

                            b1.Property<bool>("NeckPain")
                                .HasColumnType("boolean");

                            b1.Property<bool>("ShoulderPain")
                                .HasColumnType("boolean");

                            b1.Property<bool>("UpperBackPain")
                                .HasColumnType("boolean");

                            b1.HasKey("UserLifestyleProfileId");

                            b1.ToTable("UserLifestyleProfile");

                            b1.WithOwner()
                                .HasForeignKey("UserLifestyleProfileId");
                        });

                    b.OwnsOne("WorkoutRag.Models.RecoveryProfile", "Recovery", b1 =>
                        {
                            b1.Property<Guid>("UserLifestyleProfileId")
                                .HasColumnType("uuid");

                            b1.Property<int>("AverageSleepHours")
                                .HasColumnType("integer");

                            b1.Property<bool>("FeelsFatiguedAfterWork")
                                .HasColumnType("boolean");

                            b1.Property<bool>("HasChronicPain")
                                .HasColumnType("boolean");

                            b1.Property<int>("StressLevel")
                                .HasColumnType("integer");

                            b1.HasKey("UserLifestyleProfileId");

                            b1.ToTable("UserLifestyleProfile");

                            b1.WithOwner()
                                .HasForeignKey("UserLifestyleProfileId");
                        });

                    b.Navigation("Habits")
                        .IsRequired();

                    b.Navigation("Movement")
                        .IsRequired();

                    b.Navigation("Pain")
                        .IsRequired();

                    b.Navigation("Recovery")
                        .IsRequired();

                    b.Navigation("Stressors")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WorkoutRag.Models.UserSport", b =>
                {
                    b.HasOne("WorkoutRag.Models.User", "User")
                        .WithMany("Sports")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WorkoutRag.Models.WorkoutExercise", b =>
                {
                    b.HasOne("WorkoutRag.Models.Exercise", "Exercise")
                        .WithMany("WorkoutExercises")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WorkoutRag.Models.WorkoutHistory", "Workout")
                        .WithMany("WorkoutExercises")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("WorkoutRag.Models.WorkoutHistory", b =>
                {
                    b.HasOne("WorkoutRag.Models.User", "User")
                        .WithMany("WorkoutHistories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WorkoutRag.Models.Exercise", b =>
                {
                    b.Navigation("WorkoutExercises");
                });

            modelBuilder.Entity("WorkoutRag.Models.User", b =>
                {
                    b.Navigation("Diets");

                    b.Navigation("LifestyleProfile");

                    b.Navigation("Sports");

                    b.Navigation("WorkoutHistories");
                });

            modelBuilder.Entity("WorkoutRag.Models.WorkoutHistory", b =>
                {
                    b.Navigation("WorkoutExercises");
                });
#pragma warning restore 612, 618
        }
    }
}
